// ssmd-agent/src/config.ts

import { parse as parseYaml } from "https://deno.land/std@0.224.0/yaml/mod.ts";

// Expected API version - update when adding tools that require new endpoints
export const EXPECTED_API_VERSION = "1.0.0";

/**
 * Signal runner configuration file schema.
 * Matches the format generated by ssmd-operators Signal controller.
 */
export interface SignalRunnerConfig {
  nats: {
    url: string;
    stream: string;
    filter?: string;
  };
  signals: string[];
  output?: {
    prefix?: string;
  };
  filters?: {
    categories?: string[];
    tickers?: string[];
  };
}

/**
 * Load signal runner configuration from a YAML file.
 * Falls back to environment variables if file not found.
 */
export async function loadSignalRunnerConfig(configPath?: string): Promise<SignalRunnerConfig> {
  // Try to load from config file first
  if (configPath) {
    try {
      const content = await Deno.readTextFile(configPath);
      const parsed = parseYaml(content) as SignalRunnerConfig;
      return parsed;
    } catch (e) {
      if (!(e instanceof Deno.errors.NotFound)) {
        throw e;
      }
      // Fall through to env vars
    }
  }

  // Fallback to environment variables
  const signals = Deno.env.get("SIGNALS")?.split(",").map(s => s.trim()).filter(Boolean) ?? [];
  const categories = Deno.env.get("CATEGORIES")?.split(",").map(s => s.trim()).filter(Boolean);
  const tickers = Deno.env.get("TICKERS")?.split(",").map(s => s.trim()).filter(Boolean);

  return {
    nats: {
      url: Deno.env.get("NATS_URL") ?? "nats://localhost:4222",
      stream: Deno.env.get("NATS_STREAM") ?? "PROD_KALSHI",
      filter: Deno.env.get("NATS_FILTER"),
    },
    signals,
    output: {
      prefix: Deno.env.get("OUTPUT_PREFIX") ?? "signals",
    },
    filters: (categories || tickers) ? { categories, tickers } : undefined,
  };
}

export const config = {
  apiUrl: Deno.env.get("SSMD_API_URL") ?? "http://localhost:8080",
  apiKey: Deno.env.get("SSMD_DATA_API_KEY") ?? "",
  // Model name in OpenRouter format (provider/model)
  model: Deno.env.get("SSMD_MODEL") ?? "anthropic/claude-sonnet-4",
  skillsPath: Deno.env.get("SSMD_SKILLS_PATH") ?? "./skills",
  promptsPath: Deno.env.get("SSMD_PROMPTS_PATH") ?? "./prompts",
  signalsPath: Deno.env.get("SSMD_SIGNALS_PATH") ?? "./signals",
  natsUrl: Deno.env.get("NATS_URL") ?? "nats://localhost:4222",
  natsStream: Deno.env.get("NATS_STREAM") ?? "PROD_KALSHI",
  // Comma-separated list of signals to run in daemon mode
  signals: Deno.env.get("SIGNALS")?.split(",").map(s => s.trim()).filter(Boolean) ?? [],
};

export function validateConfig(): void {
  if (!config.apiKey) {
    throw new Error("SSMD_DATA_API_KEY required");
  }
  // Note: anthropicApiKey no longer required - all LLM calls go through
  // the ssmd-data proxy which handles authentication with OpenRouter
}

/**
 * Check ssmd-data API version compatibility.
 * Warns if server is older or unreachable.
 */
export async function checkApiVersion(): Promise<void> {
  try {
    const res = await fetch(`${config.apiUrl}/version`, {
      signal: AbortSignal.timeout(5000),
    });

    if (!res.ok) {
      if (res.status === 404) {
        console.warn(
          `⚠️  ssmd-data server does not support /version endpoint (server may be outdated)`
        );
        console.warn(
          `   Expected API version: ${EXPECTED_API_VERSION}. Some tools may not work.`
        );
      } else {
        console.warn(`⚠️  ssmd-data /version check failed: ${res.status}`);
      }
      return;
    }

    const { version } = await res.json() as { version: string };

    if (version !== EXPECTED_API_VERSION) {
      console.warn(
        `⚠️  API version mismatch: server=${version}, expected=${EXPECTED_API_VERSION}`
      );
      console.warn(`   Some tools may not work correctly.`);
    }
  } catch (err) {
    if (err instanceof DOMException && err.name === "TimeoutError") {
      console.warn(`⚠️  ssmd-data server not reachable at ${config.apiUrl}`);
    } else {
      console.warn(`⚠️  Failed to check API version: ${err}`);
    }
  }
}
